// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your Firebase project credentials.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOlOO1AzUPVFMmXipnxdMHOaeuYxBC_Y',
    appId: '1:736667996095:android:1f16c4d45ae1f791131b0a',
    messagingSenderId: '736667996095',
    projectId: 'debt-free-app-f3ce0',
    storageBucket: 'debt-free-app-f3ce0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE1DG7KcGQ4vyX4RoGixCCn4bkj8JQm9s',
    appId: '1:736667996095:web:0147d55deaa27d3e131b0a',
    messagingSenderId: '736667996095',
    projectId: 'debt-free-app-f3ce0',
    authDomain: 'debt-free-app-f3ce0.firebaseapp.com',
    storageBucket: 'debt-free-app-f3ce0.firebasestorage.app',
    measurementId: 'G-9ZEBMVC2Y5',
  );

}